services:
  - type: worker
    name: gitpush-worker
    env: node
    branch: main
    buildCommand: |
      npm install
      chmod +x setup.sh
      ./setup.sh
    startCommand: |
      ./setup.sh
      node gencode.js
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
    autoDeploy: true
    repo:
      branch: main
      cloneCommand: |
        git clone https://github.com/NyamaoGregoryKaiser/trics.git .
        git checkout main 