services:
  - type: worker
    name: gitpush-worker
    env: node
    branch: main
    buildCommand: npm install
    startCommand: node git-cleanup.js && node gencode.js
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
    autoDeploy: true
    cloneCommand: |
      git clone https://github.com/NyamaoGregoryKaiser/trics.git . && 
      git checkout main 